server:
  port: 8080
  context-path: /restaurant-management
  
spring:
  data:
    mongodb:
      host: ds151279.mlab.com
      port: 51279
      database: restaurant-mgmt
      username: admin
      password: admin  